CREATE TABLE `permUser` ( `idPermUser` INT NOT NULL AUTO_INCREMENT , `idUser` INT NOT NULL , `descPerm` VARCHAR(50) NOT NULL , PRIMARY KEY (`idPermUser`)) ENGINE = InnoDB;
CREATE TABLE `user` ( `idUser` INT NOT NULL AUTO_INCREMENT , `nameUser` VARCHAR(50) NOT NULL , PRIMARY KEY (`idUser`)) ENGINE = InnoDB;
CREATE TABLE `hash` ( `idHash` INT NOT NULL AUTO_INCREMENT , `id` VARCHAR(100) NOT NULL , `hash` VARCHAR(200) NOT NULL , PRIMARY KEY (`idHash`)) ENGINE = InnoDB;
ALTER TABLE `permUser` ADD CONSTRAINT `idUserKeyPerm` FOREIGN KEY (`idUser`) REFERENCES `user`(`idUser`) ON DELETE RESTRICT ON UPDATE RESTRICT;
